/**
 * ISSPF Uptime Monitor
 * ────────────────────────────────────────────────────────────────
 * A standalone Cloudflare Worker that polls the ISSPF hosts on a cron
 * schedule, classifies *how* they failed (not just that they failed),
 * stores history in KV, and alerts on state transitions.
 *
 * Why this is a separate Worker and not part of the Pages `_worker.js`:
 * Cloudflare Pages Functions do not support Cron Triggers. Only a
 * standalone Worker can run a `scheduled()` handler. See monitor/README.md.
 *
 * The point of this is diagnosis, not just a red/green light. When
 * www.isspf.com drops, the Cloudflare error code tells you whose fault it
 * is — 521 means the origin refused the connection, 522 means it never
 * answered, 524 means it answered too slowly, and an "Error establishing a
 * database connection" body means MySQL fell over. Those point at very
 * different fixes, so we record the distinction every time.
 */

// ─────────────────────────────────────────────────────────────
// CONFIG
// ─────────────────────────────────────────────────────────────

const DEFAULT_TARGETS = [
  { name: 'www',   url: 'https://www.isspf.com/' },
  { name: 'learn', url: 'https://learn.isspf.com/' },
  { name: 'go',    url: 'https://go.isspf.com/gk-report/' }
];

// Keep the most recent N incidents (state transitions). Not every check —
// a check every 5 minutes is ~8,600/month per host and KV values cap at 25 MB.
const MAX_INCIDENTS = 300;

// Daily rollups are what the uptime percentages are computed from.
const ROLLUP_RETENTION_DAYS = 90;

/**
 * Cloudflare's origin-error codes. These are generated by Cloudflare's edge
 * when it cannot get a good response from your origin server, so they are
 * strong evidence that the fault is at the WordPress host rather than in
 * DNS or Cloudflare itself.
 */
const CF_ORIGIN_ERRORS = {
  520: 'Origin returned an empty/unknown response (often a PHP crash mid-response)',
  521: 'Origin refused the connection — web server down, or firewall blocking Cloudflare IPs',
  522: 'Connection timed out — origin never completed the TCP handshake (classic overloaded host)',
  523: 'Origin unreachable — DNS/routing to the origin IP is broken',
  524: 'Origin accepted but took over 100s to respond (slow query, runaway wp-cron, bad plugin)',
  525: 'SSL handshake failed between Cloudflare and origin (expired/misconfigured origin cert)',
  526: 'Origin presented an invalid SSL certificate'
};

// ─────────────────────────────────────────────────────────────
// HANDLERS
// ─────────────────────────────────────────────────────────────

export default {
  async scheduled(event, env, ctx) {
    ctx.waitUntil(runChecks(env, 'cron'));
  },

  async fetch(request, env) {
    const url = new URL(request.url);

    // Optional shared-secret gate. If DASHBOARD_TOKEN is set, every route
    // requires ?token=<value>. If it isn't set, the dashboard is public —
    // it exposes no secrets, only up/down history.
    if (env.DASHBOARD_TOKEN && url.searchParams.get('token') !== env.DASHBOARD_TOKEN) {
      return new Response('Unauthorized', { status: 401 });
    }

    if (url.pathname === '/check') {
      const results = await runChecks(env, 'manual');
      return json({ ok: true, results });
    }

    if (url.pathname === '/history') {
      const incidents = await kvGet(env, 'incidents', []);
      return json({ ok: true, incidents });
    }

    if (url.pathname === '/status.json') {
      return json({ ok: true, ...(await buildStatus(env)) });
    }

    return new Response(await renderDashboard(env, url), {
      headers: { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store' }
    });
  }
};

// ─────────────────────────────────────────────────────────────
// CHECK LOOP
// ─────────────────────────────────────────────────────────────

async function runChecks(env, trigger) {
  const targets = parseTargets(env);
  const timeoutMs = Number(env.TIMEOUT_MS || 30000);
  const slowMs = Number(env.SLOW_MS || 5000);
  const now = new Date();

  const results = await Promise.all(
    targets.map((t) => checkTarget(t, { timeoutMs, slowMs }))
  );

  // Persist and alert sequentially so we don't race on the shared
  // `incidents` key — KV has no compare-and-swap.
  const transitions = [];
  for (const result of results) {
    await recordRollup(env, result, now);
    const transition = await recordState(env, result, now);
    if (transition) transitions.push(transition);
  }

  if (transitions.length) {
    await sendAlerts(env, transitions, trigger);
  }

  return results;
}

/**
 * Probe one target and classify the outcome.
 *
 * Two deliberate choices here:
 *
 * 1. We append a cache-busting query param and disable Cloudflare's cache.
 *    Without this a Worker fetch can be served a cached copy from
 *    Cloudflare's edge and report "up" while the WordPress origin behind it
 *    is completely dead — which is exactly the failure we're trying to see.
 *
 * 2. We read the body (capped) rather than issuing a HEAD, because a
 *    WordPress database failure returns HTTP 200 with "Error establishing a
 *    database connection" in the body. Status code alone would miss it.
 */
async function checkTarget(target, { timeoutMs, slowMs }) {
  const probeUrl = new URL(target.url);
  probeUrl.searchParams.set('_uptime', Date.now().toString(36));

  const started = Date.now();
  const base = { name: target.name, url: target.url, checked_at: new Date().toISOString() };

  let response;
  try {
    response = await fetch(probeUrl.toString(), {
      method: 'GET',
      redirect: 'follow',
      signal: AbortSignal.timeout(timeoutMs),
      headers: {
        'User-Agent': 'ISSPF-Uptime-Monitor/1.0 (+https://go.isspf.com)',
        'Cache-Control': 'no-cache',
        'Pragma': 'no-cache',
        'Accept': 'text/html'
      },
      cf: { cacheTtl: 0, cacheEverything: false }
    });
  } catch (err) {
    const ms = Date.now() - started;
    const timedOut = err.name === 'TimeoutError' || /timeout/i.test(err.message || '');
    return {
      ...base,
      up: false,
      ms,
      status: 0,
      kind: timedOut ? 'timeout' : 'unreachable',
      detail: timedOut
        ? `No response within ${timeoutMs / 1000}s — origin is hanging or Cloudflare cannot reach it`
        : `Request failed: ${err.message}`
    };
  }

  const ms = Date.now() - started;
  const status = response.status;

  // Read a bounded slice of the body — enough to fingerprint WordPress and
  // database errors without pulling a full page into memory every 5 minutes.
  let body = '';
  try {
    body = (await response.text()).slice(0, 4000);
  } catch {
    /* body unreadable; status code alone still tells us plenty */
  }

  // WordPress DB failure returns 200 or 500 with this exact string.
  if (/Error establishing a database connection/i.test(body)) {
    return {
      ...base, up: false, ms, status,
      kind: 'wp-database-down',
      detail: 'WordPress cannot reach MySQL — usually the DB server ran out of memory or hit max_connections'
    };
  }

  if (CF_ORIGIN_ERRORS[status]) {
    return {
      ...base, up: false, ms, status,
      kind: `cloudflare-${status}`,
      detail: CF_ORIGIN_ERRORS[status]
    };
  }

  if (status === 429) {
    return {
      ...base, up: false, ms, status,
      kind: 'rate-limited',
      detail: 'Origin or Cloudflare is rate-limiting requests'
    };
  }

  if (status >= 500) {
    return {
      ...base, up: false, ms, status,
      kind: 'origin-5xx',
      detail: `Origin returned ${status} — check PHP-FPM and the WordPress error log`
    };
  }

  if (status >= 400) {
    return {
      ...base, up: false, ms, status,
      kind: 'client-error',
      detail: `Unexpected ${status} on a page that should be public`
    };
  }

  if (ms > slowMs) {
    return {
      ...base, up: true, ms, status,
      kind: 'degraded',
      detail: `Responded in ${(ms / 1000).toFixed(1)}s — slow enough to be heading for a 524`
    };
  }

  return { ...base, up: true, ms, status, kind: 'up', detail: 'OK' };
}

// ─────────────────────────────────────────────────────────────
// STATE + HISTORY
// ─────────────────────────────────────────────────────────────

/**
 * Compare against the last known state and record a transition if it
 * changed. Alerting only on transitions is what stops a six-hour outage
 * from generating 72 identical emails.
 */
async function recordState(env, result, now) {
  const key = `state:${result.name}`;
  const previous = await kvGet(env, key, null);
  const wasUp = previous ? previous.up : true;
  const nowUp = result.up;

  await env.MONITOR.put(key, JSON.stringify({
    up: nowUp,
    kind: result.kind,
    status: result.status,
    ms: result.ms,
    detail: result.detail,
    since: previous && previous.up === nowUp ? previous.since : now.toISOString(),
    checked_at: result.checked_at
  }));

  // A degraded-but-serving host stays "up" for alerting purposes; we don't
  // want to page anyone because one check took 5.2 seconds.
  if (wasUp === nowUp) return null;

  const transition = {
    name: result.name,
    url: result.url,
    type: nowUp ? 'recovered' : 'down',
    kind: result.kind,
    status: result.status,
    ms: result.ms,
    detail: result.detail,
    at: now.toISOString(),
    downtime_from: previous?.since || null
  };

  const incidents = await kvGet(env, 'incidents', []);
  incidents.unshift(transition);
  await env.MONITOR.put('incidents', JSON.stringify(incidents.slice(0, MAX_INCIDENTS)));

  return transition;
}

/** Daily counters, so uptime % doesn't require replaying every check. */
async function recordRollup(env, result, now) {
  const day = now.toISOString().slice(0, 10);
  const key = `day:${result.name}:${day}`;
  const roll = await kvGet(env, key, { checks: 0, failures: 0, total_ms: 0, worst_ms: 0 });

  roll.checks += 1;
  if (!result.up) roll.failures += 1;
  roll.total_ms += result.ms;
  roll.worst_ms = Math.max(roll.worst_ms, result.ms);

  await env.MONITOR.put(key, JSON.stringify(roll), {
    expirationTtl: ROLLUP_RETENTION_DAYS * 86400
  });
}

// ─────────────────────────────────────────────────────────────
// ALERTS
// ─────────────────────────────────────────────────────────────

async function sendAlerts(env, transitions, trigger) {
  const subject = buildSubject(transitions);
  const lines = transitions.map((t) =>
    t.type === 'down'
      ? `DOWN  ${t.name} (${t.url})\n      ${t.kind}${t.status ? ` — HTTP ${t.status}` : ''}\n      ${t.detail}`
      : `UP    ${t.name} (${t.url})\n      Recovered after being down since ${t.downtime_from || 'unknown'}`
  );
  const text = `${lines.join('\n\n')}\n\nTriggered by: ${trigger}\nDashboard: ${env.DASHBOARD_URL || '(set DASHBOARD_URL to link it here)'}`;

  const jobs = [];
  if (env.RESEND_API_KEY && env.ALERT_EMAIL_TO && env.ALERT_EMAIL_FROM) {
    jobs.push(sendResend(env, subject, text));
  }
  if (env.ALERT_WEBHOOK_URL) {
    jobs.push(sendWebhook(env, `*${subject}*\n\`\`\`${text}\`\`\``));
  }

  if (!jobs.length) {
    console.warn('[monitor] State change with no alert channel configured:', subject);
    return;
  }

  // Never let a failing alert provider break the check loop.
  await Promise.allSettled(jobs);
}

function buildSubject(transitions) {
  const down = transitions.filter((t) => t.type === 'down');
  if (down.length && down.length === transitions.length) {
    return `🔴 ISSPF DOWN: ${down.map((t) => t.name).join(', ')}`;
  }
  if (!down.length) {
    return `🟢 ISSPF recovered: ${transitions.map((t) => t.name).join(', ')}`;
  }
  return `🔴 ISSPF status change: ${transitions.map((t) => `${t.name} ${t.type}`).join(', ')}`;
}

async function sendResend(env, subject, text) {
  const resp = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${env.RESEND_API_KEY}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      from: env.ALERT_EMAIL_FROM,
      to: env.ALERT_EMAIL_TO.split(',').map((s) => s.trim()).filter(Boolean),
      subject,
      text
    })
  });
  if (!resp.ok) {
    console.error('[monitor] Resend failed:', resp.status, (await resp.text()).slice(0, 300));
  }
}

/** Shaped to work with both Slack (`text`) and Discord (`content`) webhooks. */
async function sendWebhook(env, message) {
  const resp = await fetch(env.ALERT_WEBHOOK_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ text: message, content: message })
  });
  if (!resp.ok) {
    console.error('[monitor] Webhook failed:', resp.status, (await resp.text()).slice(0, 300));
  }
}

// ─────────────────────────────────────────────────────────────
// DASHBOARD
// ─────────────────────────────────────────────────────────────

async function buildStatus(env) {
  const targets = parseTargets(env);
  const today = new Date();

  const hosts = await Promise.all(targets.map(async (t) => {
    const state = await kvGet(env, `state:${t.name}`, null);
    return {
      name: t.name,
      url: t.url,
      state,
      uptime_24h: await uptimeOver(env, t.name, today, 1),
      uptime_7d: await uptimeOver(env, t.name, today, 7),
      uptime_30d: await uptimeOver(env, t.name, today, 30)
    };
  }));

  return { hosts, incidents: (await kvGet(env, 'incidents', [])).slice(0, 25) };
}

async function uptimeOver(env, name, endDate, days) {
  let checks = 0;
  let failures = 0;
  let totalMs = 0;

  for (let i = 0; i < days; i++) {
    const d = new Date(endDate.getTime() - i * 86400000).toISOString().slice(0, 10);
    const roll = await kvGet(env, `day:${name}:${d}`, null);
    if (!roll) continue;
    checks += roll.checks;
    failures += roll.failures;
    totalMs += roll.total_ms;
  }

  if (!checks) return null;
  return {
    pct: ((checks - failures) / checks) * 100,
    checks,
    failures,
    avg_ms: Math.round(totalMs / checks)
  };
}

async function renderDashboard(env, url) {
  const { hosts, incidents } = await buildStatus(env);
  const token = env.DASHBOARD_TOKEN ? `?token=${encodeURIComponent(url.searchParams.get('token') || '')}` : '';

  const cards = hosts.map((h) => {
    const s = h.state;
    const up = s ? s.up : null;
    const cls = up === null ? 'unknown' : up ? (s.kind === 'degraded' ? 'warn' : 'ok') : 'bad';
    const label = up === null ? 'No data yet' : up ? (s.kind === 'degraded' ? 'Degraded' : 'Up') : 'Down';
    return `
      <div class="card ${cls}">
        <div class="card-head">
          <span class="dot"></span>
          <h2>${esc(h.name)}</h2>
          <span class="badge">${esc(label)}</span>
        </div>
        <a class="url" href="${esc(h.url)}">${esc(h.url)}</a>
        ${s ? `<p class="detail">${esc(s.detail)}${s.status ? ` <span class="mono">(HTTP ${s.status}, ${s.ms}ms)</span>` : ''}</p>
        <p class="since">Since ${esc(fmt(s.since))}</p>` : '<p class="detail">Waiting for the first scheduled check.</p>'}
        <div class="uptimes">
          ${['24h', '7d', '30d'].map((k, i) => {
            const u = [h.uptime_24h, h.uptime_7d, h.uptime_30d][i];
            return `<div><span class="k">${k}</span><span class="v">${u ? u.pct.toFixed(2) + '%' : '—'}</span>${u ? `<span class="sub">${u.avg_ms}ms avg</span>` : ''}</div>`;
          }).join('')}
        </div>
      </div>`;
  }).join('');

  const rows = incidents.length
    ? incidents.map((i) => `
        <tr class="${i.type === 'down' ? 'bad' : 'ok'}">
          <td class="mono">${esc(fmt(i.at))}</td>
          <td>${esc(i.name)}</td>
          <td><span class="pill ${i.type === 'down' ? 'bad' : 'ok'}">${esc(i.type)}</span></td>
          <td class="mono">${esc(i.kind)}${i.status ? ` / ${i.status}` : ''}</td>
          <td>${esc(i.detail)}</td>
        </tr>`).join('')
    : '<tr><td colspan="5" class="empty">No incidents recorded yet.</td></tr>';

  return `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>ISSPF Uptime</title>
<style>
  :root{--bg:#0f1115;--panel:#171a21;--line:#252a34;--fg:#e7ebf0;--mut:#8b95a5;
        --ok:#2ecc71;--bad:#ff5d5d;--warn:#f5a623;}
  @media(prefers-color-scheme:light){:root{--bg:#f6f7f9;--panel:#fff;--line:#e3e6ea;--fg:#12151a;--mut:#667085;}}
  *{box-sizing:border-box}
  body{margin:0;padding:32px 20px;background:var(--bg);color:var(--fg);
       font:15px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif}
  .wrap{max-width:1000px;margin:0 auto}
  h1{font-size:22px;margin:0 0 4px}
  .lede{color:var(--mut);margin:0 0 28px;font-size:14px}
  .grid{display:grid;gap:16px;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));margin-bottom:32px}
  .card{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:18px}
  .card-head{display:flex;align-items:center;gap:9px;margin-bottom:6px}
  .card h2{font-size:16px;margin:0;flex:1;text-transform:uppercase;letter-spacing:.05em}
  .dot{width:10px;height:10px;border-radius:50%;background:var(--mut);flex:none}
  .card.ok .dot{background:var(--ok)} .card.bad .dot{background:var(--bad)} .card.warn .dot{background:var(--warn)}
  .badge{font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:.06em;color:var(--mut)}
  .card.ok .badge{color:var(--ok)} .card.bad .badge{color:var(--bad)} .card.warn .badge{color:var(--warn)}
  .url{color:var(--mut);font-size:13px;text-decoration:none;word-break:break-all}
  .url:hover{text-decoration:underline}
  .detail{margin:10px 0 2px;font-size:13px}
  .since{margin:0;color:var(--mut);font-size:12px}
  .uptimes{display:flex;gap:18px;margin-top:14px;padding-top:14px;border-top:1px solid var(--line)}
  .uptimes .k{display:block;color:var(--mut);font-size:11px;text-transform:uppercase;letter-spacing:.06em}
  .uptimes .v{display:block;font-size:17px;font-weight:600;font-variant-numeric:tabular-nums}
  .uptimes .sub{display:block;color:var(--mut);font-size:11px}
  h3{font-size:14px;text-transform:uppercase;letter-spacing:.06em;color:var(--mut);margin:0 0 12px}
  .tablewrap{overflow-x:auto;background:var(--panel);border:1px solid var(--line);border-radius:12px}
  table{width:100%;border-collapse:collapse;font-size:13px;min-width:680px}
  th{text-align:left;padding:11px 14px;color:var(--mut);font-size:11px;text-transform:uppercase;
     letter-spacing:.06em;border-bottom:1px solid var(--line);font-weight:600}
  td{padding:11px 14px;border-bottom:1px solid var(--line);vertical-align:top}
  tr:last-child td{border-bottom:none}
  .mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px}
  .pill{display:inline-block;padding:2px 8px;border-radius:99px;font-size:11px;font-weight:600;text-transform:uppercase}
  .pill.bad{background:rgba(255,93,93,.15);color:var(--bad)}
  .pill.ok{background:rgba(46,204,113,.15);color:var(--ok)}
  .empty{color:var(--mut);text-align:center;padding:28px}
  .foot{color:var(--mut);font-size:12px;margin-top:22px}
  .foot a{color:inherit}
</style></head>
<body><div class="wrap">
  <h1>ISSPF Uptime</h1>
  <p class="lede">Checked every 5 minutes from Cloudflare's edge, with caching bypassed so a cached copy can't mask a dead origin.</p>
  <div class="grid">${cards}</div>
  <h3>Recent state changes</h3>
  <div class="tablewrap"><table>
    <thead><tr><th>When (UTC)</th><th>Host</th><th>Change</th><th>Classification</th><th>What it means</th></tr></thead>
    <tbody>${rows}</tbody>
  </table></div>
  <p class="foot">
    <a href="/check${token}">Run a check now</a> ·
    <a href="/status.json${token}">status.json</a> ·
    <a href="/history${token}">full history</a>
  </p>
</div></body></html>`;
}

// ─────────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────────

function parseTargets(env) {
  if (!env.TARGETS) return DEFAULT_TARGETS;
  try {
    const parsed = JSON.parse(env.TARGETS);
    return Array.isArray(parsed) && parsed.length ? parsed : DEFAULT_TARGETS;
  } catch {
    console.error('[monitor] TARGETS is not valid JSON — falling back to defaults');
    return DEFAULT_TARGETS;
  }
}

async function kvGet(env, key, fallback) {
  const raw = await env.MONITOR.get(key);
  if (!raw) return fallback;
  try {
    return JSON.parse(raw);
  } catch {
    return fallback;
  }
}

function json(data, status = 200) {
  return new Response(JSON.stringify(data, null, 2), {
    status,
    headers: { 'Content-Type': 'application/json', 'Cache-Control': 'no-store' }
  });
}

function fmt(iso) {
  if (!iso) return 'unknown';
  return iso.replace('T', ' ').replace(/\.\d+Z$/, ' UTC');
}

function esc(s) {
  return String(s ?? '').replace(/[&<>"']/g, (c) =>
    ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}
